INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Uzbequistão','S',0,'UZB'),
	 ('1','Cabo Verde','S',0,'CPV'),
	 ('3','México','N',0,'MEX'),
	 ('3','Cabo Verde','S',0,'CPV'),
	 ('4','Cabo Verde','S',0,'CPV'),
	 ('5','Cabo Verde','S',0,'CPV'),
	 ('6','Cabo Verde','S',0,'CPV'),
	 ('19','México','N',0,'MEX'),
	 ('8','Cabo Verde','S',0,'CPV'),
	 ('9','Cabo Verde','S',0,'CPV');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Cabo Verde','S',0,'CPV'),
	 ('11','Cabo Verde','S',0,'CPV'),
	 ('12','Cabo Verde','S',0,'CPV'),
	 ('18','Irã','S',0,'IRN'),
	 ('19','Irã','S',0,'IRN'),
	 ('20','Irã','S',0,'IRN'),
	 ('4','Coreia do Sul','S',0,'KOR'),
	 ('5','Coreia do Sul','S',0,'KOR'),
	 ('6','Coreia do Sul','S',0,'KOR'),
	 ('7','Coreia do Sul','S',0,'KOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('8','Coreia do Sul','S',0,'KOR'),
	 ('9','Coreia do Sul','S',0,'KOR'),
	 ('10','Coreia do Sul','S',0,'KOR'),
	 ('11','Coreia do Sul','S',0,'KOR'),
	 ('12','Coreia do Sul','S',0,'KOR'),
	 ('13','Coreia do Sul','S',0,'KOR'),
	 ('14','Coreia do Sul','S',0,'KOR'),
	 ('15','Coreia do Sul','S',0,'KOR'),
	 ('13','Escócia','S',0,'SCO'),
	 ('14','Escócia','S',0,'SCO');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('15','Escócia','S',0,'SCO'),
	 ('16','Escócia','S',0,'SCO'),
	 ('17','Escócia','S',0,'SCO'),
	 ('18','Escócia','S',0,'SCO'),
	 ('20','Escócia','S',0,'SCO'),
	 ('19','Escócia','S',0,'SCO'),
	 ('1','México','S',0,'MEX'),
	 ('2','México','S',0,'MEX'),
	 ('4','México','S',0,'MEX'),
	 ('5','México','S',0,'MEX');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('6','México','S',0,'MEX'),
	 ('7','México','S',0,'MEX'),
	 ('8','México','S',0,'MEX'),
	 ('9','México','S',0,'MEX'),
	 ('10','México','S',0,'MEX'),
	 ('11','México','S',0,'MEX'),
	 ('12','México','S',0,'MEX'),
	 ('13','México','S',0,'MEX'),
	 ('14','México','S',0,'MEX'),
	 ('15','México','S',0,'MEX');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','México','S',0,'MEX'),
	 ('17','México','S',0,'MEX'),
	 ('18','México','S',0,'MEX'),
	 ('20','México','S',0,'MEX'),
	 ('1','Japão','S',0,'JPN'),
	 ('2','Japão','S',0,'JPN'),
	 ('3','Japão','S',0,'JPN'),
	 ('4','Japão','S',0,'JPN'),
	 ('5','Japão','S',0,'JPN'),
	 ('6','Japão','S',0,'JPN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('7','Japão','S',0,'JPN'),
	 ('8','Japão','S',0,'JPN'),
	 ('10','Japão','S',0,'JPN'),
	 ('11','Japão','S',0,'JPN'),
	 ('8','Colômbia','S',0,'COL'),
	 ('9','Colômbia','S',0,'COL'),
	 ('10','Colômbia','S',0,'COL'),
	 ('11','Colômbia','S',0,'COL'),
	 ('12','Colômbia','S',0,'COL'),
	 ('13','Colômbia','S',0,'COL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('14','Colômbia','S',0,'COL'),
	 ('15','Colômbia','S',0,'COL'),
	 ('16','Colômbia','S',0,'COL'),
	 ('17','Colômbia','S',0,'COL'),
	 ('18','Colômbia','S',0,'COL'),
	 ('19','Colômbia','S',0,'COL'),
	 ('20','Colômbia','S',0,'COL'),
	 ('13','Arábia Saudita','S',0,'KSA'),
	 ('14','Arábia Saudita','S',0,'KSA'),
	 ('15','Arábia Saudita','S',0,'KSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','Arábia Saudita','S',0,'KSA'),
	 ('4','Brasil','S',0,'BRA'),
	 ('10','Brasil','S',0,'BRA'),
	 ('15','Brasil','S',0,'BRA'),
	 ('1','Brasil','S',0,'BRA'),
	 ('1','Argélia','S',0,'ALG'),
	 ('6','Argélia','S',0,'ALG'),
	 ('2','Cabo Verde','N',0,'CPV'),
	 ('7','Cabo Verde','N',0,'CPV'),
	 ('17','Arábia Saudita','N',0,'KSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('18','Arábia Saudita','N',0,'KSA'),
	 ('2','Argélia','N',0,'ALG'),
	 ('3','Argélia','N',0,'ALG'),
	 ('5','Argélia','N',0,'ALG'),
	 ('8','Argélia','N',0,'ALG'),
	 ('10','Argélia','N',0,'ALG'),
	 ('11','Argélia','N',0,'ALG'),
	 ('16','Argélia','N',0,'ALG'),
	 ('18','Argélia','N',0,'ALG'),
	 ('19','Argélia','N',0,'ALG');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Argélia','S',0,'ALG'),
	 ('13','Argélia','S',0,'ALG'),
	 ('14','Argélia','S',0,'ALG'),
	 ('15','Argélia','S',0,'ALG'),
	 ('17','Argélia','S',0,'ALG'),
	 ('20','Argélia','S',0,'ALG'),
	 ('4','Argélia','S',0,'ALG'),
	 ('7','Argélia','S',0,'ALG'),
	 ('9','Argélia','S',0,'ALG'),
	 ('16','Coreia do Sul','S',0,'KOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('17','Coreia do Sul','S',0,'KOR'),
	 ('18','Coreia do Sul','S',0,'KOR'),
	 ('19','Coreia do Sul','S',0,'KOR'),
	 ('16','Canadá','S',0,'CAN'),
	 ('17','Canadá','S',0,'CAN'),
	 ('18','Canadá','S',0,'CAN'),
	 ('19','Canadá','S',0,'CAN'),
	 ('20','Canadá','S',0,'CAN'),
	 ('7','Holanda','S',0,'NED'),
	 ('8','Holanda','S',0,'NED');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('9','Holanda','S',0,'NED'),
	 ('10','Holanda','S',0,'NED'),
	 ('11','Holanda','S',0,'NED'),
	 ('12','Holanda','S',0,'NED'),
	 ('13','Holanda','S',0,'NED'),
	 ('14','Holanda','S',0,'NED'),
	 ('15','Holanda','S',0,'NED'),
	 ('16','Holanda','S',0,'NED'),
	 ('17','Holanda','S',0,'NED'),
	 ('18','Holanda','S',0,'NED');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('19','Holanda','S',0,'NED'),
	 ('20','Holanda','S',0,'NED'),
	 ('7','Equador','S',0,'ECU'),
	 ('8','Equador','S',0,'ECU'),
	 ('11','Equador','S',0,'ECU'),
	 ('12','Equador','S',0,'ECU'),
	 ('13','Equador','S',0,'ECU'),
	 ('14','Equador','S',0,'ECU'),
	 ('15','Equador','S',0,'ECU'),
	 ('16','Equador','S',0,'ECU');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('17','Equador','S',0,'ECU'),
	 ('18','Equador','S',0,'ECU'),
	 ('19','Equador','S',0,'ECU'),
	 ('20','Equador','S',0,'ECU'),
	 ('2','Equador','S',0,'ECU'),
	 ('3','Equador','S',0,'ECU'),
	 ('4','Equador','S',0,'ECU'),
	 ('5','Equador','S',0,'ECU'),
	 ('1','Nova Zelândia','S',0,'NZL'),
	 ('2','Nova Zelândia','S',0,'NZL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Nova Zelândia','S',0,'NZL'),
	 ('5','Nova Zelândia','S',0,'NZL'),
	 ('6','Nova Zelândia','S',0,'NZL'),
	 ('7','Nova Zelândia','S',0,'NZL'),
	 ('8','Nova Zelândia','S',0,'NZL'),
	 ('9','Nova Zelândia','S',0,'NZL'),
	 ('10','Nova Zelândia','S',0,'NZL'),
	 ('11','Nova Zelândia','S',0,'NZL'),
	 ('13','Nova Zelândia','S',0,'NZL'),
	 ('14','Nova Zelândia','S',0,'NZL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('15','Nova Zelândia','S',0,'NZL'),
	 ('16','Nova Zelândia','S',0,'NZL'),
	 ('17','Nova Zelândia','S',0,'NZL'),
	 ('17','Portugal','S',0,'POR'),
	 ('18','Portugal','S',0,'POR'),
	 ('19','Portugal','S',0,'POR'),
	 ('20','Portugal','S',0,'POR'),
	 ('1','França','S',0,'FRA'),
	 ('2','França','S',0,'FRA'),
	 ('3','França','S',0,'FRA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('5','França','S',0,'FRA'),
	 ('6','França','S',0,'FRA'),
	 ('7','França','S',0,'FRA'),
	 ('8','França','S',0,'FRA'),
	 ('9','França','S',0,'FRA'),
	 ('10','França','S',0,'FRA'),
	 ('11','França','S',0,'FRA'),
	 ('13','França','S',0,'FRA'),
	 ('14','França','S',0,'FRA'),
	 ('15','França','S',0,'FRA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','França','S',0,'FRA'),
	 ('17','França','S',0,'FRA'),
	 ('19','França','S',0,'FRA'),
	 ('20','França','S',0,'FRA'),
	 ('19','Uzbequistão','S',0,'UZB'),
	 ('20','Uzbequistão','S',0,'UZB'),
	 ('2','Uzbequistão','S',0,'UZB'),
	 ('4','Uzbequistão','S',0,'UZB'),
	 ('1','Bélgica','S',0,'BEL'),
	 ('2','Bélgica','S',0,'BEL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Bélgica','S',0,'BEL'),
	 ('4','Bélgica','S',0,'BEL'),
	 ('5','Bélgica','S',0,'BEL'),
	 ('6','Bélgica','S',0,'BEL'),
	 ('7','Bélgica','S',0,'BEL'),
	 ('9','Bélgica','S',0,'BEL'),
	 ('10','Bélgica','S',0,'BEL'),
	 ('11','Bélgica','S',0,'BEL'),
	 ('12','Bélgica','S',0,'BEL'),
	 ('13','Bélgica','S',0,'BEL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('14','Bélgica','S',0,'BEL'),
	 ('15','Bélgica','S',0,'BEL'),
	 ('16','Bélgica','S',0,'BEL'),
	 ('17','Bélgica','S',0,'BEL'),
	 ('19','Bélgica','S',0,'BEL'),
	 ('20','Bélgica','S',0,'BEL'),
	 ('1','Argentina','S',0,'ARG'),
	 ('2','Argentina','S',0,'ARG'),
	 ('4','Argentina','S',0,'ARG'),
	 ('5','Argentina','S',0,'ARG');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('6','Argentina','S',0,'ARG'),
	 ('7','Argentina','S',0,'ARG'),
	 ('8','Argentina','S',0,'ARG'),
	 ('9','Argentina','S',0,'ARG'),
	 ('10','Argentina','S',0,'ARG'),
	 ('11','Argentina','S',0,'ARG'),
	 ('12','Argentina','S',0,'ARG'),
	 ('13','Argentina','S',0,'ARG'),
	 ('14','Argentina','S',0,'ARG'),
	 ('15','Argentina','S',0,'ARG');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','Argentina','S',0,'ARG'),
	 ('17','Argentina','S',0,'ARG'),
	 ('18','Argentina','S',0,'ARG'),
	 ('19','Argentina','S',0,'ARG'),
	 ('16','Turquia','S',0,'TUR'),
	 ('17','Turquia','S',0,'TUR'),
	 ('18','Turquia','S',0,'TUR'),
	 ('19','Turquia','S',0,'TUR'),
	 ('7','Paraguai','S',0,'PAR'),
	 ('8','Paraguai','S',0,'PAR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('9','Paraguai','S',0,'PAR'),
	 ('20','Turquia','N',0,'TUR'),
	 ('6','Equador','N',0,'ECU'),
	 ('9','Equador','N',0,'ECU'),
	 ('10','Equador','N',0,'ECU'),
	 ('20','Coreia do Sul','S',0,'KOR'),
	 ('1','Marrocos','S',0,'MAR'),
	 ('1','FWC','S',0,'FWC'),
	 ('10','Paraguai','S',0,'PAR'),
	 ('11','Paraguai','S',0,'PAR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Paraguai','S',0,'PAR'),
	 ('13','Paraguai','S',0,'PAR'),
	 ('14','Paraguai','S',0,'PAR'),
	 ('15','Paraguai','S',0,'PAR'),
	 ('16','Paraguai','S',0,'PAR'),
	 ('17','Paraguai','S',0,'PAR'),
	 ('20','Paraguai','S',0,'PAR'),
	 ('1','Rep. Tcheca','S',0,'CZE'),
	 ('2','Rep. Tcheca','S',0,'CZE'),
	 ('3','Rep. Tcheca','S',0,'CZE');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Rep. Tcheca','S',0,'CZE'),
	 ('5','Rep. Tcheca','S',0,'CZE'),
	 ('6','Rep. Tcheca','S',0,'CZE'),
	 ('7','Rep. Tcheca','S',0,'CZE'),
	 ('8','Rep. Tcheca','S',0,'CZE'),
	 ('9','Rep. Tcheca','S',0,'CZE'),
	 ('10','Rep. Tcheca','S',0,'CZE'),
	 ('11','Rep. Tcheca','S',0,'CZE'),
	 ('12','Rep. Tcheca','S',0,'CZE'),
	 ('13','Rep. Tcheca','S',0,'CZE');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('14','Jordânia','S',0,'JOR'),
	 ('15','Jordânia','S',0,'JOR'),
	 ('16','Jordânia','S',0,'JOR'),
	 ('17','Jordânia','S',0,'JOR'),
	 ('18','Jordânia','S',0,'JOR'),
	 ('19','Jordânia','S',0,'JOR'),
	 ('20','Jordânia','S',0,'JOR'),
	 ('1','Estados Unidos','S',0,'USA'),
	 ('2','Estados Unidos','S',0,'USA'),
	 ('3','Estados Unidos','S',0,'USA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Estados Unidos','S',0,'USA'),
	 ('5','Estados Unidos','S',0,'USA'),
	 ('8','Estados Unidos','S',0,'USA'),
	 ('9','Estados Unidos','S',0,'USA'),
	 ('10','Estados Unidos','S',0,'USA'),
	 ('11','Estados Unidos','S',0,'USA'),
	 ('12','Estados Unidos','S',0,'USA'),
	 ('13','Estados Unidos','S',0,'USA'),
	 ('14','Estados Unidos','S',0,'USA'),
	 ('15','Estados Unidos','S',0,'USA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','Estados Unidos','S',0,'USA'),
	 ('17','Estados Unidos','S',0,'USA'),
	 ('18','Estados Unidos','S',0,'USA'),
	 ('19','Estados Unidos','S',0,'USA'),
	 ('20','Estados Unidos','S',0,'USA'),
	 ('1','Congo','S',0,'COD'),
	 ('2','Congo','S',0,'COD'),
	 ('3','Congo','S',0,'COD'),
	 ('6','Congo','S',0,'COD'),
	 ('8','Congo','S',0,'COD');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('9','Congo','S',0,'COD'),
	 ('10','Congo','S',0,'COD'),
	 ('11','Congo','S',0,'COD'),
	 ('12','Congo','S',0,'COD'),
	 ('13','Congo','S',0,'COD'),
	 ('14','Congo','S',0,'COD'),
	 ('15','Congo','S',0,'COD'),
	 ('16','Congo','S',0,'COD'),
	 ('17','Congo','S',0,'COD'),
	 ('18','Congo','S',0,'COD');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('19','Congo','S',0,'COD'),
	 ('20','Congo','S',0,'COD'),
	 ('1','Iraque','S',0,'IRQ'),
	 ('2','Iraque','S',0,'IRQ'),
	 ('3','Iraque','S',0,'IRQ'),
	 ('4','Iraque','S',0,'IRQ'),
	 ('5','Iraque','S',0,'IRQ'),
	 ('7','Iraque','S',0,'IRQ'),
	 ('8','Iraque','S',0,'IRQ'),
	 ('9','Iraque','S',0,'IRQ');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Iraque','S',0,'IRQ'),
	 ('11','Iraque','S',0,'IRQ'),
	 ('12','Iraque','S',0,'IRQ'),
	 ('14','Iraque','S',0,'IRQ'),
	 ('15','Iraque','S',0,'IRQ'),
	 ('16','Iraque','S',0,'IRQ'),
	 ('3','Catar','S',0,'QAT'),
	 ('4','Catar','S',0,'QAT'),
	 ('5','Catar','S',0,'QAT'),
	 ('7','Catar','S',0,'QAT');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('8','Catar','S',0,'QAT'),
	 ('9','Catar','S',0,'QAT'),
	 ('10','Catar','S',0,'QAT'),
	 ('11','Catar','S',0,'QAT'),
	 ('12','Catar','S',0,'QAT'),
	 ('14','Catar','S',0,'QAT'),
	 ('15','Catar','S',0,'QAT'),
	 ('16','Catar','S',0,'QAT'),
	 ('17','Catar','S',0,'QAT'),
	 ('18','Catar','S',0,'QAT');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('19','Catar','S',0,'QAT'),
	 ('20','Catar','S',0,'QAT'),
	 ('1','Espanha','S',0,'ESP'),
	 ('4','Espanha','S',0,'ESP'),
	 ('5','Espanha','S',0,'ESP'),
	 ('6','Espanha','S',0,'ESP'),
	 ('7','Espanha','S',0,'ESP'),
	 ('8','Espanha','S',0,'ESP'),
	 ('9','Espanha','S',0,'ESP'),
	 ('10','Espanha','S',0,'ESP');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('11','Espanha','S',0,'ESP'),
	 ('12','Espanha','S',0,'ESP'),
	 ('13','Espanha','S',0,'ESP'),
	 ('14','Espanha','S',0,'ESP'),
	 ('15','Espanha','S',0,'ESP'),
	 ('16','Espanha','S',0,'ESP'),
	 ('17','Espanha','S',0,'ESP'),
	 ('18','Espanha','S',0,'ESP'),
	 ('19','Espanha','S',0,'ESP'),
	 ('20','Espanha','S',0,'ESP');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Noruega','S',0,'NOR'),
	 ('2','Noruega','S',0,'NOR'),
	 ('4','Curaçao','S',0,'CUW'),
	 ('5','Curaçao','S',0,'CUW'),
	 ('6','Curaçao','S',0,'CUW'),
	 ('7','Curaçao','S',0,'CUW'),
	 ('8','Curaçao','S',0,'CUW'),
	 ('9','Curaçao','S',0,'CUW'),
	 ('10','Curaçao','S',0,'CUW'),
	 ('11','Curaçao','S',0,'CUW');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Curaçao','S',0,'CUW'),
	 ('13','Curaçao','S',0,'CUW'),
	 ('15','Curaçao','S',0,'CUW'),
	 ('6','Catar','N',0,'QAT'),
	 ('13','Catar','N',0,'QAT'),
	 ('6','Estados Unidos','N',0,'USA'),
	 ('16','Curaçao','S',0,'CUW'),
	 ('17','Curaçao','S',0,'CUW'),
	 ('18','Curaçao','S',0,'CUW'),
	 ('19','Curaçao','S',0,'CUW');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Curaçao','S',0,'CUW'),
	 ('1','Senegal','S',0,'SEN'),
	 ('2','Senegal','S',0,'SEN'),
	 ('3','Senegal','S',0,'SEN'),
	 ('4','Senegal','S',0,'SEN'),
	 ('5','Senegal','S',0,'SEN'),
	 ('6','Senegal','S',0,'SEN'),
	 ('7','Senegal','S',0,'SEN'),
	 ('8','Senegal','S',0,'SEN'),
	 ('9','Senegal','S',0,'SEN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Senegal','S',0,'SEN'),
	 ('11','Senegal','S',0,'SEN'),
	 ('12','Senegal','S',0,'SEN'),
	 ('13','Senegal','S',0,'SEN'),
	 ('14','Senegal','S',0,'SEN'),
	 ('15','Senegal','S',0,'SEN'),
	 ('16','Senegal','S',0,'SEN'),
	 ('17','Senegal','S',0,'SEN'),
	 ('18','Senegal','S',0,'SEN'),
	 ('19','Senegal','S',0,'SEN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Senegal','S',0,'SEN'),
	 ('1','Panamá','S',0,'PAN'),
	 ('7','Egito','S',0,'EGY'),
	 ('8','Egito','S',0,'EGY'),
	 ('9','Egito','S',0,'EGY'),
	 ('10','Egito','S',0,'EGY'),
	 ('11','Egito','S',0,'EGY'),
	 ('13','Egito','S',0,'EGY'),
	 ('14','Egito','S',0,'EGY'),
	 ('15','Egito','S',0,'EGY');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('17','Egito','S',0,'EGY'),
	 ('19','Egito','S',0,'EGY'),
	 ('1','Austrália','S',0,'AUS'),
	 ('2','Austrália','S',0,'AUS'),
	 ('3','Austrália','S',0,'AUS'),
	 ('4','Austrália','S',0,'AUS'),
	 ('5','Austrália','S',0,'AUS'),
	 ('6','Austrália','S',0,'AUS'),
	 ('7','Austrália','S',0,'AUS'),
	 ('8','Austrália','S',0,'AUS');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('9','Austrália','S',0,'AUS'),
	 ('10','Austrália','S',0,'AUS'),
	 ('11','Austrália','S',0,'AUS'),
	 ('12','Austrália','S',0,'AUS'),
	 ('13','Austrália','S',0,'AUS'),
	 ('14','Austrália','S',0,'AUS'),
	 ('15','Austrália','S',0,'AUS'),
	 ('16','Austrália','S',0,'AUS'),
	 ('17','Austrália','S',0,'AUS'),
	 ('18','Austrália','S',0,'AUS');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('19','Austrália','S',0,'AUS'),
	 ('20','Austrália','S',0,'AUS'),
	 ('1','Gana','S',0,'GHA'),
	 ('2','Gana','S',0,'GHA'),
	 ('4','Gana','S',0,'GHA'),
	 ('5','Gana','S',0,'GHA'),
	 ('6','Gana','S',0,'GHA'),
	 ('7','Gana','S',0,'GHA'),
	 ('8','Gana','S',0,'GHA'),
	 ('9','Gana','S',0,'GHA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Gana','S',0,'GHA'),
	 ('11','Gana','S',0,'GHA'),
	 ('12','Gana','S',0,'GHA'),
	 ('13','Gana','S',0,'GHA'),
	 ('14','Gana','S',0,'GHA'),
	 ('15','Gana','S',0,'GHA'),
	 ('16','Gana','S',0,'GHA'),
	 ('17','Gana','S',0,'GHA'),
	 ('18','Gana','S',0,'GHA'),
	 ('19','Gana','S',0,'GHA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Gana','S',0,'GHA'),
	 ('2','Alemanha','S',0,'GER'),
	 ('3','Alemanha','S',0,'GER'),
	 ('4','Alemanha','S',0,'GER'),
	 ('5','Alemanha','S',0,'GER'),
	 ('7','Alemanha','S',0,'GER'),
	 ('8','Alemanha','S',0,'GER'),
	 ('9','Alemanha','S',0,'GER'),
	 ('10','Alemanha','S',0,'GER'),
	 ('9','África do Sul','S',0,'RSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','África do Sul','S',0,'RSA'),
	 ('11','África do Sul','S',0,'RSA'),
	 ('12','África do Sul','S',0,'RSA'),
	 ('13','África do Sul','S',0,'RSA'),
	 ('14','África do Sul','S',0,'RSA'),
	 ('15','África do Sul','S',0,'RSA'),
	 ('16','África do Sul','S',0,'RSA'),
	 ('1','Arábia Saudita','S',0,'KSA'),
	 ('2','Arábia Saudita','S',0,'KSA'),
	 ('3','Arábia Saudita','S',0,'KSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Arábia Saudita','S',0,'KSA'),
	 ('5','Arábia Saudita','S',0,'KSA'),
	 ('6','Arábia Saudita','S',0,'KSA'),
	 ('7','Arábia Saudita','S',0,'KSA'),
	 ('8','Arábia Saudita','S',0,'KSA'),
	 ('9','Arábia Saudita','S',0,'KSA'),
	 ('10','Arábia Saudita','S',0,'KSA'),
	 ('11','Arábia Saudita','S',0,'KSA'),
	 ('12','Arábia Saudita','S',0,'KSA'),
	 ('19','Arábia Saudita','S',0,'KSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Arábia Saudita','S',0,'KSA'),
	 ('19','Brasil','S',0,'BRA'),
	 ('1','Equador','S',0,'ECU'),
	 ('9','Turquia','S',0,'TUR'),
	 ('10','Turquia','S',0,'TUR'),
	 ('11','Turquia','S',0,'TUR'),
	 ('12','Turquia','S',0,'TUR'),
	 ('13','Turquia','S',0,'TUR'),
	 ('14','Turquia','S',0,'TUR'),
	 ('15','Turquia','S',0,'TUR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Paraguai','S',0,'PAR'),
	 ('2','Paraguai','S',0,'PAR'),
	 ('3','Paraguai','S',0,'PAR'),
	 ('4','Paraguai','S',0,'PAR'),
	 ('5','Paraguai','S',0,'PAR'),
	 ('6','Paraguai','S',0,'PAR'),
	 ('14','FWC','S',0,'FWC'),
	 ('3','Brasil','S',0,'BRA'),
	 ('18','Brasil','S',0,'BRA'),
	 ('17','Brasil','S',0,'BRA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Brasil','S',0,'BRA'),
	 ('16','Brasil','S',0,'BRA'),
	 ('13','Brasil','S',0,'BRA'),
	 ('11','Brasil','S',0,'BRA'),
	 ('12','Brasil','S',0,'BRA'),
	 ('8','Brasil','S',0,'BRA'),
	 ('7','Brasil','S',0,'BRA'),
	 ('5','Brasil','S',0,'BRA'),
	 ('14','Brasil','S',0,'BRA'),
	 ('17','Iraque','S',0,'IRQ');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('2','Marrocos','S',0,'MAR'),
	 ('3','Marrocos','S',0,'MAR'),
	 ('4','Marrocos','S',0,'MAR'),
	 ('5','Marrocos','S',0,'MAR'),
	 ('6','Marrocos','S',0,'MAR'),
	 ('7','Marrocos','S',0,'MAR'),
	 ('8','Marrocos','S',0,'MAR'),
	 ('9','Marrocos','S',0,'MAR'),
	 ('10','Marrocos','S',0,'MAR'),
	 ('11','Marrocos','S',0,'MAR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('2','Brasil','N',0,'BRA'),
	 ('13','Marrocos','S',0,'MAR'),
	 ('14','Marrocos','S',0,'MAR'),
	 ('15','Marrocos','S',0,'MAR'),
	 ('16','Marrocos','S',0,'MAR'),
	 ('17','Marrocos','S',0,'MAR'),
	 ('6','Brasil','N',0,'BRA'),
	 ('19','Marrocos','S',0,'MAR'),
	 ('9','Brasil','N',0,'BRA'),
	 ('12','Marrocos','N',0,'MAR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('2','Costa do Marfim','S',0,'CIV'),
	 ('3','Costa do Marfim','S',0,'CIV'),
	 ('4','Costa do Marfim','S',0,'CIV'),
	 ('5','Costa do Marfim','S',0,'CIV'),
	 ('6','Costa do Marfim','S',0,'CIV'),
	 ('7','Costa do Marfim','S',0,'CIV'),
	 ('8','Costa do Marfim','S',0,'CIV'),
	 ('9','Costa do Marfim','S',0,'CIV'),
	 ('10','Costa do Marfim','S',0,'CIV'),
	 ('11','Costa do Marfim','S',0,'CIV');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Costa do Marfim','S',0,'CIV'),
	 ('13','Costa do Marfim','S',0,'CIV'),
	 ('14','Costa do Marfim','S',0,'CIV'),
	 ('15','Costa do Marfim','S',0,'CIV'),
	 ('18','Marrocos','N',0,'MAR'),
	 ('11','Noruega','S',0,'NOR'),
	 ('18','Iraque','S',0,'IRQ'),
	 ('19','Iraque','S',0,'IRQ'),
	 ('20','Iraque','S',0,'IRQ'),
	 ('1','Catar','S',0,'QAT');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('2','Catar','S',0,'QAT'),
	 ('14','Cabo Verde','S',0,'CPV'),
	 ('15','Cabo Verde','S',0,'CPV'),
	 ('16','Cabo Verde','S',0,'CPV'),
	 ('17','Cabo Verde','S',0,'CPV'),
	 ('18','Cabo Verde','S',0,'CPV'),
	 ('1','Bósnia','S',0,'BIH'),
	 ('1','Croácia','S',0,'CRO'),
	 ('2','Croácia','S',0,'CRO'),
	 ('3','Croácia','S',0,'CRO');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Haiti','S',0,'HAI'),
	 ('5','Croácia','S',0,'CRO'),
	 ('6','Croácia','S',0,'CRO'),
	 ('7','Croácia','S',0,'CRO'),
	 ('8','Croácia','S',0,'CRO'),
	 ('10','Croácia','S',0,'CRO'),
	 ('11','Croácia','S',0,'CRO'),
	 ('12','Croácia','S',0,'CRO'),
	 ('13','Croácia','S',0,'CRO'),
	 ('15','Croácia','S',0,'CRO');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','Croácia','S',0,'CRO'),
	 ('17','Croácia','S',0,'CRO'),
	 ('1','Escócia','S',0,'SCO'),
	 ('1','Canadá','S',0,'CAN'),
	 ('2','Canadá','S',0,'CAN'),
	 ('4','Haiti','S',0,'HAI'),
	 ('5','Haiti','S',0,'HAI'),
	 ('6','Haiti','S',0,'HAI'),
	 ('7','Haiti','S',0,'HAI'),
	 ('8','Haiti','S',0,'HAI');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('9','Haiti','S',0,'HAI'),
	 ('10','Haiti','S',0,'HAI'),
	 ('11','Haiti','S',0,'HAI'),
	 ('12','Haiti','S',0,'HAI'),
	 ('13','Haiti','S',0,'HAI'),
	 ('14','Haiti','S',0,'HAI'),
	 ('15','Haiti','S',0,'HAI'),
	 ('16','Haiti','S',0,'HAI'),
	 ('2','Haiti','N',0,'HAI'),
	 ('3','Haiti','N',0,'HAI');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Marrocos','N',0,'MAR'),
	 ('7','Estados Unidos','N',0,'USA'),
	 ('18','Paraguai','N',0,'PAR'),
	 ('19','Paraguai','N',0,'PAR'),
	 ('1','Alemanha','N',0,'GER'),
	 ('6','Alemanha','N',0,'GER'),
	 ('14','Curaçao','N',0,'CUW'),
	 ('1','Costa do Marfim','N',0,'CIV'),
	 ('16','Costa do Marfim','N',0,'CIV'),
	 ('8','Bélgica','N',0,'BEL');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('18','Bélgica','N',0,'BEL'),
	 ('12','Egito','N',0,'EGY'),
	 ('16','Egito','N',0,'EGY'),
	 ('18','Egito','N',0,'EGY'),
	 ('20','Egito','N',0,'EGY'),
	 ('3','Nova Zelândia','N',0,'NZL'),
	 ('12','Nova Zelândia','N',0,'NZL'),
	 ('2','Espanha','N',0,'ESP'),
	 ('3','Espanha','N',0,'ESP'),
	 ('13','Cabo Verde','N',0,'CPV');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','França','N',0,'FRA'),
	 ('17','Costa do Marfim','S',0,'CIV'),
	 ('18','Costa do Marfim','S',0,'CIV'),
	 ('19','Costa do Marfim','S',0,'CIV'),
	 ('20','Costa do Marfim','S',0,'CIV'),
	 ('2','Bósnia','S',0,'BIH'),
	 ('3','Bósnia','S',0,'BIH'),
	 ('4','Bósnia','S',0,'BIH'),
	 ('5','Bósnia','S',0,'BIH'),
	 ('6','Bósnia','S',0,'BIH');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('7','Bósnia','S',0,'BIH'),
	 ('8','Bósnia','S',0,'BIH'),
	 ('9','Bósnia','S',0,'BIH'),
	 ('10','Bósnia','S',0,'BIH'),
	 ('11','Bósnia','S',0,'BIH'),
	 ('12','Bósnia','S',0,'BIH'),
	 ('13','Bósnia','S',0,'BIH'),
	 ('14','Bósnia','S',0,'BIH'),
	 ('15','Bósnia','S',0,'BIH'),
	 ('16','Bósnia','S',0,'BIH');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('17','Bósnia','S',0,'BIH'),
	 ('18','Bósnia','S',0,'BIH'),
	 ('19','Bósnia','S',0,'BIH'),
	 ('19','Croácia','S',0,'CRO'),
	 ('20','Croácia','S',0,'CRO'),
	 ('5','Tunísia','S',0,'TUN'),
	 ('6','Tunísia','S',0,'TUN'),
	 ('7','Tunísia','S',0,'TUN'),
	 ('8','Tunísia','S',0,'TUN'),
	 ('9','Tunísia','S',0,'TUN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Tunísia','S',0,'TUN'),
	 ('11','Tunísia','S',0,'TUN'),
	 ('12','Tunísia','S',0,'TUN'),
	 ('13','Tunísia','S',0,'TUN'),
	 ('2','Escócia','S',0,'SCO'),
	 ('3','Escócia','S',0,'SCO'),
	 ('4','Escócia','S',0,'SCO'),
	 ('1','Coreia do Sul','S',0,'KOR'),
	 ('2','Coreia do Sul','S',0,'KOR'),
	 ('3','Coreia do Sul','S',0,'KOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('5','Escócia','S',0,'SCO'),
	 ('6','Escócia','S',0,'SCO'),
	 ('7','Escócia','S',0,'SCO'),
	 ('8','Escócia','S',0,'SCO'),
	 ('9','Escócia','S',0,'SCO'),
	 ('10','Escócia','S',0,'SCO'),
	 ('11','Escócia','S',0,'SCO'),
	 ('12','Escócia','S',0,'SCO'),
	 ('20','Bósnia','N',0,'BIH'),
	 ('12','França','N',0,'FRA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('18','França','N',0,'FRA'),
	 ('6','Iraque','N',0,'IRQ'),
	 ('13','Iraque','N',0,'IRQ'),
	 ('3','Argentina','N',0,'ARG'),
	 ('4','Congo','N',0,'COD'),
	 ('5','Congo','N',0,'COD'),
	 ('7','Congo','N',0,'COD'),
	 ('4','Croácia','N',0,'CRO'),
	 ('9','Croácia','N',0,'CRO'),
	 ('14','Croácia','N',0,'CRO');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('18','Croácia','N',0,'CRO'),
	 ('3','Gana','N',0,'GHA'),
	 ('12','Japão','S',0,'JPN'),
	 ('14','Japão','S',0,'JPN'),
	 ('15','Japão','S',0,'JPN'),
	 ('16','Japão','S',0,'JPN'),
	 ('17','Japão','S',0,'JPN'),
	 ('18','Japão','S',0,'JPN'),
	 ('19','Japão','S',0,'JPN'),
	 ('20','Japão','S',0,'JPN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('17','África do Sul','S',0,'RSA'),
	 ('18','África do Sul','S',0,'RSA'),
	 ('19','África do Sul','S',0,'RSA'),
	 ('20','África do Sul','S',0,'RSA'),
	 ('2','Colômbia','S',0,'COL'),
	 ('3','Colômbia','S',0,'COL'),
	 ('4','Colômbia','S',0,'COL'),
	 ('5','Colômbia','S',0,'COL'),
	 ('7','Colômbia','S',0,'COL'),
	 ('13','Japão','N',0,'JPN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Colômbia','N',0,'COL'),
	 ('6','Colômbia','N',0,'COL'),
	 ('18','Nova Zelândia','S',0,'NZL'),
	 ('20','Nova Zelândia','S',0,'NZL'),
	 ('1','Portugal','S',0,'POR'),
	 ('2','Portugal','S',0,'POR'),
	 ('3','Portugal','S',0,'POR'),
	 ('4','Portugal','S',0,'POR'),
	 ('5','Portugal','S',0,'POR'),
	 ('6','Portugal','S',0,'POR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('8','Portugal','S',0,'POR'),
	 ('10','Portugal','S',0,'POR'),
	 ('12','Portugal','S',0,'POR'),
	 ('13','Portugal','S',0,'POR'),
	 ('14','Portugal','S',0,'POR'),
	 ('16','Portugal','S',0,'POR'),
	 ('19','Nova Zelândia','N',0,'NZL'),
	 ('7','Portugal','N',0,'POR'),
	 ('9','Portugal','N',0,'POR'),
	 ('11','Portugal','N',0,'POR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('14','Rep. Tcheca','S',0,'CZE'),
	 ('15','Rep. Tcheca','S',0,'CZE'),
	 ('16','Rep. Tcheca','S',0,'CZE'),
	 ('17','Rep. Tcheca','S',0,'CZE'),
	 ('18','Rep. Tcheca','S',0,'CZE'),
	 ('19','Rep. Tcheca','S',0,'CZE'),
	 ('20','Rep. Tcheca','S',0,'CZE'),
	 ('1','Jordânia','S',0,'JOR'),
	 ('2','Jordânia','S',0,'JOR'),
	 ('3','Jordânia','S',0,'JOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Jordânia','S',0,'JOR'),
	 ('6','Jordânia','S',0,'JOR'),
	 ('7','Jordânia','S',0,'JOR'),
	 ('8','Jordânia','S',0,'JOR'),
	 ('9','Jordânia','S',0,'JOR'),
	 ('10','Jordânia','S',0,'JOR'),
	 ('11','Jordânia','S',0,'JOR'),
	 ('13','Jordânia','S',0,'JOR'),
	 ('5','Jordânia','N',0,'JOR'),
	 ('12','Jordânia','N',0,'JOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Noruega','S',0,'NOR'),
	 ('4','Noruega','S',0,'NOR'),
	 ('5','Noruega','S',0,'NOR'),
	 ('6','Noruega','S',0,'NOR'),
	 ('7','Noruega','S',0,'NOR'),
	 ('8','Noruega','S',0,'NOR'),
	 ('9','Noruega','S',0,'NOR'),
	 ('10','Noruega','S',0,'NOR'),
	 ('12','Noruega','S',0,'NOR'),
	 ('14','Noruega','S',0,'NOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('15','Noruega','S',0,'NOR'),
	 ('16','Noruega','S',0,'NOR'),
	 ('17','Noruega','S',0,'NOR'),
	 ('18','Noruega','S',0,'NOR'),
	 ('19','Noruega','S',0,'NOR'),
	 ('20','Noruega','S',0,'NOR'),
	 ('1','Curaçao','S',0,'CUW'),
	 ('2','Curaçao','S',0,'CUW'),
	 ('3','Curaçao','S',0,'CUW'),
	 ('13','Noruega','N',0,'NOR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('11','Alemanha','S',0,'GER'),
	 ('12','Alemanha','S',0,'GER'),
	 ('13','Alemanha','S',0,'GER'),
	 ('15','Alemanha','S',0,'GER'),
	 ('16','Alemanha','S',0,'GER'),
	 ('19','Alemanha','S',0,'GER'),
	 ('20','Alemanha','S',0,'GER'),
	 ('1','África do Sul','S',0,'RSA'),
	 ('2','África do Sul','S',0,'RSA'),
	 ('3','África do Sul','S',0,'RSA');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','África do Sul','S',0,'RSA'),
	 ('5','África do Sul','S',0,'RSA'),
	 ('6','África do Sul','S',0,'RSA'),
	 ('7','África do Sul','S',0,'RSA'),
	 ('8','África do Sul','S',0,'RSA'),
	 ('4','FWC','N',0,'FWC'),
	 ('14','Alemanha','N',0,'GER'),
	 ('17','Alemanha','N',0,'GER'),
	 ('18','Alemanha','N',0,'GER'),
	 ('3','Canadá','S',0,'CAN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('4','Canadá','S',0,'CAN'),
	 ('5','Canadá','S',0,'CAN'),
	 ('6','Canadá','S',0,'CAN'),
	 ('7','Canadá','S',0,'CAN'),
	 ('8','Canadá','S',0,'CAN'),
	 ('9','Canadá','S',0,'CAN'),
	 ('10','Canadá','S',0,'CAN'),
	 ('11','Canadá','S',0,'CAN'),
	 ('12','Canadá','S',0,'CAN'),
	 ('13','Canadá','S',0,'CAN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('14','Canadá','S',0,'CAN'),
	 ('15','Canadá','S',0,'CAN'),
	 ('1','Holanda','S',0,'NED'),
	 ('2','Holanda','S',0,'NED'),
	 ('3','Holanda','S',0,'NED'),
	 ('4','Holanda','S',0,'NED'),
	 ('5','Holanda','S',0,'NED'),
	 ('6','Holanda','S',0,'NED'),
	 ('2','Suécia','S',0,'SWE'),
	 ('3','Suécia','S',0,'SWE');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Suíça','N',0,'SUI'),
	 ('14','Suíça','N',0,'SUI'),
	 ('1','Suécia','N',0,'SWE'),
	 ('19','Suécia','N',0,'SWE'),
	 ('4','Suécia','S',0,'SWE'),
	 ('5','Suécia','S',0,'SWE'),
	 ('6','Suécia','S',0,'SWE'),
	 ('7','Suécia','S',0,'SWE'),
	 ('8','Suécia','S',0,'SWE'),
	 ('9','Suécia','S',0,'SWE');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('10','Suécia','S',0,'SWE'),
	 ('11','Suécia','S',0,'SWE'),
	 ('12','Suécia','S',0,'SWE'),
	 ('13','Suécia','S',0,'SWE'),
	 ('14','Suécia','S',0,'SWE'),
	 ('15','Suécia','S',0,'SWE'),
	 ('16','Suécia','S',0,'SWE'),
	 ('17','Suécia','S',0,'SWE'),
	 ('18','Suécia','S',0,'SWE'),
	 ('20','Suécia','S',0,'SWE');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('2','Suíça','S',0,'SUI'),
	 ('3','Suíça','S',0,'SUI'),
	 ('4','Suíça','S',0,'SUI'),
	 ('5','Suíça','S',0,'SUI'),
	 ('6','Suíça','S',0,'SUI'),
	 ('7','Suíça','S',0,'SUI'),
	 ('8','Suíça','S',0,'SUI'),
	 ('9','Suíça','S',0,'SUI'),
	 ('10','Suíça','S',0,'SUI'),
	 ('11','Suíça','S',0,'SUI');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Suíça','S',0,'SUI'),
	 ('13','Suíça','S',0,'SUI'),
	 ('15','Suíça','S',0,'SUI'),
	 ('16','Suíça','S',0,'SUI'),
	 ('17','Suíça','S',0,'SUI'),
	 ('18','Suíça','S',0,'SUI'),
	 ('19','Suíça','S',0,'SUI'),
	 ('20','Suíça','S',0,'SUI'),
	 ('1','Tunísia','S',0,'TUN'),
	 ('2','Tunísia','S',0,'TUN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Tunísia','S',0,'TUN'),
	 ('4','Tunísia','S',0,'TUN'),
	 ('5','Uzbequistão','S',0,'UZB'),
	 ('20','Argentina','S',0,'ARG'),
	 ('2','Turquia','S',0,'TUR'),
	 ('3','Turquia','S',0,'TUR'),
	 ('4','Turquia','S',0,'TUR'),
	 ('6','Turquia','S',0,'TUR'),
	 ('7','Turquia','S',0,'TUR'),
	 ('8','Turquia','S',0,'TUR');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Coca-Cola','S',0,'CC'),
	 ('2','Coca-Cola','S',0,'CC'),
	 ('3','Coca-Cola','S',0,'CC'),
	 ('4','Coca-Cola','S',0,'CC'),
	 ('5','Coca-Cola','S',0,'CC'),
	 ('6','Coca-Cola','S',0,'CC'),
	 ('7','Coca-Cola','S',0,'CC'),
	 ('8','Coca-Cola','S',0,'CC'),
	 ('9','Coca-Cola','S',0,'CC'),
	 ('10','Coca-Cola','S',0,'CC');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('11','Coca-Cola','S',0,'CC'),
	 ('12','Coca-Cola','S',0,'CC'),
	 ('13','Coca-Cola','S',0,'CC'),
	 ('14','Coca-Cola','S',0,'CC'),
	 ('14','Tunísia','S',0,'TUN'),
	 ('15','Tunísia','S',0,'TUN'),
	 ('16','Tunísia','S',0,'TUN'),
	 ('17','Tunísia','S',0,'TUN'),
	 ('18','Tunísia','S',0,'TUN'),
	 ('19','Tunísia','S',0,'TUN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('20','Tunísia','S',0,'TUN'),
	 ('1','Uruguai','S',0,'URU'),
	 ('2','Uruguai','S',0,'URU'),
	 ('3','Uruguai','S',0,'URU'),
	 ('4','Uruguai','S',0,'URU'),
	 ('5','Uruguai','S',0,'URU'),
	 ('6','Uruguai','S',0,'URU'),
	 ('8','Uruguai','S',0,'URU'),
	 ('9','Uruguai','S',0,'URU'),
	 ('10','Uruguai','S',0,'URU');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('12','Uruguai','S',0,'URU'),
	 ('13','Uruguai','S',0,'URU'),
	 ('14','Uruguai','S',0,'URU'),
	 ('15','Uruguai','S',0,'URU'),
	 ('16','Uruguai','S',0,'URU'),
	 ('17','Uruguai','S',0,'URU'),
	 ('18','Uruguai','S',0,'URU'),
	 ('19','Uruguai','S',0,'URU'),
	 ('20','Uruguai','S',0,'URU'),
	 ('1','Uzbequistão','S',0,'UZB');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('6','Uzbequistão','S',0,'UZB'),
	 ('7','Uzbequistão','S',0,'UZB'),
	 ('8','Uzbequistão','S',0,'UZB'),
	 ('9','Uzbequistão','S',0,'UZB'),
	 ('10','Uzbequistão','S',0,'UZB'),
	 ('11','Uzbequistão','S',0,'UZB'),
	 ('12','Uzbequistão','S',0,'UZB'),
	 ('13','Uzbequistão','S',0,'UZB'),
	 ('14','Uzbequistão','S',0,'UZB'),
	 ('15','Uzbequistão','S',0,'UZB');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('16','Uzbequistão','S',0,'UZB'),
	 ('17','Uzbequistão','S',0,'UZB'),
	 ('18','Uzbequistão','S',0,'UZB'),
	 ('1','Turquia','N',0,'TUR'),
	 ('5','Turquia','N',0,'TUR'),
	 ('7','Uruguai','N',0,'URU'),
	 ('11','Uruguai','N',0,'URU'),
	 ('2','FWC','S',0,'FWC'),
	 ('3','FWC','S',0,'FWC'),
	 ('17','Haiti','S',0,'HAI');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('6','FWC','S',0,'FWC'),
	 ('7','FWC','S',0,'FWC'),
	 ('8','FWC','S',0,'FWC'),
	 ('11','FWC','S',0,'FWC'),
	 ('12','FWC','S',0,'FWC'),
	 ('13','FWC','S',0,'FWC'),
	 ('9','FWC','S',0,'FWC'),
	 ('10','FWC','S',0,'FWC'),
	 ('15','FWC','S',0,'FWC'),
	 ('20','FWC','S',0,'FWC');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('18','Haiti','S',0,'HAI'),
	 ('18','FWC','S',0,'FWC'),
	 ('19','Haiti','S',0,'HAI'),
	 ('16','FWC','S',0,'FWC'),
	 ('20','Haiti','S',0,'HAI'),
	 ('5','FWC','N',0,'FWC'),
	 ('17','FWC','N',0,'FWC'),
	 ('19','FWC','N',0,'FWC'),
	 ('19','Cabo Verde','S',0,'CPV'),
	 ('20','Cabo Verde','S',0,'CPV');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('1','Áustria','S',0,'AUT'),
	 ('2','Áustria','S',0,'AUT'),
	 ('3','Áustria','S',0,'AUT'),
	 ('4','Áustria','S',0,'AUT'),
	 ('5','Áustria','S',0,'AUT'),
	 ('6','Áustria','S',0,'AUT'),
	 ('7','Áustria','S',0,'AUT'),
	 ('8','Áustria','S',0,'AUT'),
	 ('9','Áustria','S',0,'AUT'),
	 ('10','Áustria','S',0,'AUT');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('11','Áustria','S',0,'AUT'),
	 ('12','Áustria','S',0,'AUT'),
	 ('13','Áustria','S',0,'AUT'),
	 ('14','Áustria','S',0,'AUT'),
	 ('15','Áustria','S',0,'AUT'),
	 ('17','Áustria','S',0,'AUT'),
	 ('19','Áustria','S',0,'AUT'),
	 ('20','Áustria','S',0,'AUT'),
	 ('1','Irã','S',0,'IRN'),
	 ('2','Irã','S',0,'IRN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Irã','S',0,'IRN'),
	 ('4','Irã','S',0,'IRN'),
	 ('5','Irã','S',0,'IRN'),
	 ('6','Irã','S',0,'IRN'),
	 ('7','Irã','S',0,'IRN'),
	 ('8','Irã','S',0,'IRN'),
	 ('9','Irã','S',0,'IRN'),
	 ('10','Irã','S',0,'IRN'),
	 ('11','Irã','S',0,'IRN'),
	 ('12','Irã','S',0,'IRN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('13','Irã','S',0,'IRN'),
	 ('14','Irã','S',0,'IRN'),
	 ('15','Irã','S',0,'IRN'),
	 ('16','Irã','S',0,'IRN'),
	 ('17','Irã','S',0,'IRN'),
	 ('16','Áustria','N',0,'AUT'),
	 ('18','Áustria','N',0,'AUT'),
	 ('9','Japão','S',0,'JPN'),
	 ('15','Portugal','S',0,'POR'),
	 ('2','Panamá','S',0,'PAN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Panamá','S',0,'PAN'),
	 ('4','Panamá','S',0,'PAN'),
	 ('5','Panamá','S',0,'PAN'),
	 ('6','Panamá','S',0,'PAN'),
	 ('7','Panamá','S',0,'PAN'),
	 ('8','Panamá','S',0,'PAN'),
	 ('9','Panamá','S',0,'PAN'),
	 ('10','Panamá','S',0,'PAN'),
	 ('11','Panamá','S',0,'PAN'),
	 ('12','Panamá','S',0,'PAN');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('13','Panamá','S',0,'PAN'),
	 ('14','Panamá','S',0,'PAN'),
	 ('15','Panamá','S',0,'PAN'),
	 ('16','Panamá','S',0,'PAN'),
	 ('17','Panamá','S',0,'PAN'),
	 ('18','Panamá','S',0,'PAN'),
	 ('19','Panamá','S',0,'PAN'),
	 ('20','Panamá','S',0,'PAN'),
	 ('1','Inglaterra','S',0,'ENG'),
	 ('2','Inglaterra','S',0,'ENG');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Inglaterra','S',0,'ENG'),
	 ('4','Inglaterra','S',0,'ENG'),
	 ('5','Inglaterra','S',0,'ENG'),
	 ('6','Inglaterra','S',0,'ENG'),
	 ('7','Inglaterra','S',0,'ENG'),
	 ('8','Inglaterra','S',0,'ENG'),
	 ('9','Inglaterra','S',0,'ENG'),
	 ('10','Inglaterra','S',0,'ENG'),
	 ('11','Inglaterra','S',0,'ENG'),
	 ('12','Inglaterra','S',0,'ENG');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('13','Inglaterra','S',0,'ENG'),
	 ('14','Inglaterra','S',0,'ENG'),
	 ('15','Inglaterra','S',0,'ENG'),
	 ('16','Inglaterra','S',0,'ENG'),
	 ('17','Inglaterra','S',0,'ENG'),
	 ('18','Inglaterra','S',0,'ENG'),
	 ('19','Inglaterra','S',0,'ENG'),
	 ('20','Inglaterra','S',0,'ENG'),
	 ('1','Egito','S',0,'EGY'),
	 ('2','Egito','S',0,'EGY');
INSERT INTO figurinhas (numero,selecao,possui,quant_rep,abreviacao) VALUES
	 ('3','Egito','S',0,'EGY'),
	 ('4','Egito','S',0,'EGY'),
	 ('5','Egito','S',0,'EGY'),
	 ('6','Egito','N',0,'EGY');
